# torch.tensor()

In [ ]:
#import不是pytorch
import torch

In [2]:
a = [1,2,3.]
print(a)
type(a)

[1, 2, 3.0]


list

In [ ]:
b = torch.tensor(a)
type(b) # 返回的是对象的类：<class 'torch.Tensor'>
b.dtype  # 推荐写法，返回数据类型：torch.float32

torch.float32

In [ ]:
type(b) # 返回的是对象的类：<class 'torch.Tensor'>

torch.Tensor

In [14]:
import numpy as np
np.random.normal(0,1,(2,3)) # 生成一个2行3列的二维数组，元素服从均值为0，标准差为1的正态分布
np.random.normal(0,1,(2,3)).dtype # 返回数据类型：float64
np.random.normal(2,3) 

3.530527216902296

In [15]:
np.random.normal(2,3) # 生成一个元素服从均值为2，标准差为3的正态分布的随机数

3.3483499759351227

In [16]:
np.random.normal((2,3))

array([2.79052718, 3.36726588])

In [17]:
a= np.random.normal((2,3))
a

array([1.47644137, 3.90547014])

In [18]:
torch.tensor(a)

tensor([1.4764, 3.9055], dtype=torch.float64)

# torch.zeros_like()

In [27]:
b=torch.tensor(np.random.normal((2,3)))
print(b)
c=torch.zeros_like(b)
c

tensor([2.1141, 3.4707], dtype=torch.float64)


tensor([0., 0.], dtype=torch.float64)

In [25]:
d=torch.ones_like(b)
d

tensor([1., 1.], dtype=torch.float64)

In [ ]:
wo=[1.,2.,3.]
e=torch.rand_like(torch.tensor(wo)) # 生成一个和wo形状相同的张量，元素服从0到1的均匀分布
e

tensor([0.6977, 0.9681, 0.2745])

# torch.rand

In [ ]:
#可以传入元组
torch.rand((2,3)) 

tensor([[0.7735, 0.1603, 0.3661],
        [0.0294, 0.1933, 0.8252]])

In [32]:
torch.rand(2,3) # 生成一个2行3列的二维张量，元素服从0到1的均匀分布

tensor([[0.3153, 0.6622, 0.2725],
        [0.5681, 0.0369, 0.1392]])

In [ ]:
torch.rand([2,3]) #可以传入列表

tensor([[0.5331, 0.7510, 0.7794],
        [0.6223, 0.1213, 0.5759]])

In [35]:
shape = (2, 3,)

ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# tensor的属性

In [37]:
a=torch.rand((2,2))
print(a.dtype)
print(a.shape)
print(a.device)

torch.float32
torch.Size([2, 2])
cpu


# tensor的操作

## 移动到GPU.to

In [ ]:
# We move our tensor to the current accelerator if available
# 如果张量大 会很耗时和内存
if torch.accelerator.is_available():
    a = a.to(torch.accelerator.current_accelerator())

## chunck

In [ ]:
B = torch.randn(5, 2) # 生成一个5行2列的二维张量，元素服从均值为0，标准差为1的正态分布

# 想分成 3 块
res = torch.chunk(B, chunks=3, dim=0)

print(len(res))       # 结果还是 3 块
print(res[0].shape)   # torch.Size([2, 2])
print(res[1].shape)   # torch.Size([2, 2])
print(res[2].shape)   # torch.Size([1, 2]) -> 最后一块补齐剩下的
print(B)         

3
torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([1, 2])
tensor([[ 0.5681,  2.1899],
        [ 0.1354, -0.8674],
        [-0.0271, -0.5992],
        [ 0.2426, -0.0546],
        [ 0.7293, -0.9387]])


In [ ]:
torch.randn(100, 1) * 0.1 